# Generated by Django 4.0.4 on 2022-05-27 18:53

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0, 0), srid=4326),
            preserve_default=False,
        ),
    ]
