# Generated by Django 4.0.5 on 2022-06-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='current_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='main.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='liked_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='who_liked', to='main.userprofile'),
            preserve_default=False,
        ),
    ]
